services:
  feat-api:
    image: feat.api:e2e
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=EndToEnd
      - Caching__Type=Memory
      - ASPNETCORE_URLS=https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=e2e
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx